readme.md

Important change

---

content/releases-and-versions/versions.md

Flutter master channel update included an update to the dart version as well.
This PR updates version info with the new numbers.

Update software versions

---

content/getting-started/automatic-language-detection.md
content/getting-started/codemagic-github-app.md
content/getting-started/flutter-project-requirements.md
content/getting-started/github-organization-accounts.md
content/getting-started/signup.md
content/releases-and-versions/release-notes.md

Added the GitHub app integration

GitHub app

---

content/building/access-private-git-submodules.md

Updated requirements about using SSH keys and added an example for generating a SSH key.

Accessing private dependencies

---

content/getting-started/adding-apps-from-custom-sources.md

Added information about how to find the clone URL and fixed a typo in examples.

Update clone URL information

---

content/building/yaml.md

Changed docs as advanced configuration is moved to sidebar and not in beta anymore

Advanced configuration is moved to sidebar

---

content/building/yaml.md

Add new tools to environment section

---

assets/js/search.js

Edge n-gram tokenizer + k1 tuning.
✅ Search works as usual for _full_ matches
✅ Search works on incomplete matches
✅ Search gives relevant results
✅ Search prioritizes matches in header
✅ Search for terms with underscores, such as `BUILD_NUMBER`
✅ Search for command line parameters, like `--build-name`
✅ Search for env variables, like `$FCI_BUILD_DIR`
✅ Search for command line commands, like `ssh-agent -s`
✅ Search for bash paths, like `#!/usr/bin/env`

Incomplete matching search

---

assets/js/search.js

Would allow to search for strings like `codemagic.yaml` and `app-release.apk`.

No dot removal from the middle of a word

---

content/getting-started/adding-apps-from-custom-sources.md

- Changed field names in Add application flow
- Added a section about changing repository access details

Add info about changing repository access settings

---

content/code-signing/android-code-signing.md

Changed the domain name from flutter.io to flutter.dev

Update the link to flutter website

---

content/building/dependency-caching.md

I'm not english native but I think this is a typo : caching instead of cashing. Many thanks for your product !

Corrected typo on dependency-caching.md

---

content/rest-api/applications.md
content/rest-api/builds.md

* Add **Retrieve an application** call
* Add **Get build status** call
* Add `curl` request for all the calls

Update Codemagic API Docs

---

content/building/yaml.md

fix 2 broken links (nbsp) and prettifying 1 link (so that a viewer doesn't need to scroll)

fix cli-tools broken links

---

content/building/yaml.md

Adds `instance_type` variable to YAML docs

add instance type to yaml

---

content/building/environment-variables.md

using GUI to modify environment variables is only available for Flutter projects not all projects. This is confusing and not clear at all from documentation. Separated, clarified and adjusted the sections to make more sense.

Update modifying environment variables via GUI

---

content/publishing/github-release.md

The publishing option was never documented, created a new page. The patterns feature is already in live

github release docs

---

content/rest-api/applications.md

We now support a synchronous endpoint for creating encrypted environment variables.

Encrypt var api

---

content/yaml/yaml.md

Add an example about expanded form for YAML scripts. Also a way to run a python script.

document expanded yaml scripts

---

content/building/access-private-git-submodules.md
content/building/building-android-app-bundles.md
content/building/building-for-the-web.md
content/code-signing/android-code-signing.md
content/custom-scripts/load-firebase-configuration.md
content/getting-started/setting-up.md
content/publishing/publish-build-artifacts-to-amazon-s3.md
content/publishing/publishing-to-app-store.md
content/publishing/publishing-to-google-play.md
content/releases-and-versions/release-notes.md
content/troubleshooting/accessing-builder-machine-via-ssh.md
content/yaml/building-a-native-android-app.md
content/yaml/yaml.md

To improve local docs experience and shorten the markdown a bit

remove absolute doc refs

---

content/building/environment-variables.md

Regarding https://github.com/NevercodeHQ/codemagic-support/issues/82
That's the shortest approach I found, but adding Priit to review as maybe he knows better approaches.
Tested on this app https://github.com/NevercodeHQ/triage/tree/master/flutter_plugin_examples/google_maps_flutter_example, it worked

Explain how to put env vars inside of app with example of google maps api key

---

assets/js/main.js
assets/scss/main.scss

Highlight current section and scroll table of contents according to it

Use the same table of contents as is used in blog.codemagic.io

---

content/yaml/building-a-native-android-app.md
content/yaml/building-a-native-ios-app.md
content/yaml/building-a-react-native-app.md

Updated YAML guides for React Native, native iOS and native Android so they include a full workflow example.

Added workflow examples for React Native, native iOS and native Android

---

content/releases-and-versions/release-notes.md

Updated the release notes with the following topics:
- Support for multiple team owners
- Using App Store Connect API for Apple Developer Portal integration

august releases

---

assets/scss/_variables.scss
assets/scss/main.scss
layouts/_default/baseof.html

currently the only way to go back to "/" page is "Documentation" link in header

make sidebar header link to the main page

---

content/rest-api/applications.md
content/rest-api/builds.md

Noticed minor formatting issues in JSON examples for API docs, these are the fixes.

fix indents, spaces and other formatting issues in JSON examples

---

content/getting-started/building-a-react-native-app.md
content/getting-started/building-an-ionic-app.md
content/getting-started/building_a_native_app_with_flutter_module.md

Proposed documentation for building **Ionic Capacitor** and **Ionic Cordova** apps.

Ionic documentation added

---

content/billing/billing.md
content/teams/teams.md
content/teams/users.md

- Updated the pages about teams and billing
- Added a new page about how we count users in teams

Pricing changes for teams

---

content/billing/billing.md

Change card

---

content/publishing-yaml/distribution.md

Please maybe rephrase in a more nice way, or drop possibly unneeded info

note on github app limitation

---

content/publishing-yaml/distribution.md

Update Slack integration

---

content/building/github-checks.md
content/building/running-locally.md
content/building/scheduling.md

Added a new page for scheduled builds

Document scheduled builds

---

content/building/build-versioning.md

See https://mikefarah.gitbook.io/yq/v/v4.x/upgrading-from-v3#reading-with-default-value :-)

Fix build number fetching instruction with yq v4

---

config.yml
content/notes/release-notes.md
content/specs/versions.md
content/specs/versions2.md

Separated Release notes from the Build machine specs

New category for release notes

---

content/building/access-private-git-submodules.md

Note about using multiple ssh keys

using multiple ssh keys

---

content/specs/versions.md
content/specs/versions2.md

update versions after latest base image update

update versions reports

---

content/specs/versions-linux.md

zip will be installed during next base image update

remove zip from linux specs

---

content/getting-started/yaml.md
content/specs/machine-type.md
content/specs/versions-linux.md
content/specs/versions.md
content/specs/versions2.md
content/specs/versions3.md

Main changes are in these two screenshots:

Update machine specs to make them more clear for linux build machines

---

content/flutter/automatic-build-triggering.md
content/flutter/flutter-projects.md
content/getting-started/building-a-flutter-app.md
content/getting-started/building-a-native-android-app.md
content/getting-started/building-a-native-ios-app.md
content/getting-started/building-a-react-native-app.md
content/getting-started/building-an-ionic-app.md

I've updated the getting started guides with the steps from the new build setup flow.

New build setup flow

---

content/billing/billing.md

Related to adding the "Pay invoice" button

Add info about overdue invoices

---

content/building/build-versioning.md

Update get ios build number with platform argument

---

content/building/encrypting.md
content/building/environment-variables.md
content/getting-started/building-a-native-android-app.md
content/getting-started/building-a-native-ios-app.md
content/getting-started/building-a-react-native-app.md
content/getting-started/building-an-ionic-app.md

- Edited the getting started guides to match the new flow
- Edited the docs related to environment variables and encrypting them

Changes related to yaml settings improvements

---

content/getting-started/signup.md
content/knowledge-base/add-a-git-tag-with-app-version.md
content/knowledge-base/generating-an-ssh-key.md
content/knowledge-base/google-play-api.md
content/knowledge-base/load-firebase-configuration.md
content/knowledge-base/migrate-to-github-app.md
content/knowledge-base/upload-custom-artifacts.md

Migrating from GH OAuth to GH App

---

content/code-signing/android-code-signing.md

@nevercode-kevin 
Can you confirm this [youtube video](https://www.youtube.com/watch?v=lYp9MAfouXE) corresponds to what we have in the [Flutter android codesigning docs](https://docs.codemagic.io/code-signing/android-code-signing/)?
I think it made the most sense to add the video here:

Add Flutter workflow editor Android code signing video

---

content/specs/versions-linux.md
content/specs/versions.md
content/specs/versions2.md
content/specs/versions3.md

Base image update @ 13-04-2021

Base image update @ 13-04-2021

---

content/getting-started/yaml.md
content/knowledge-base/validate-yaml.md

- Added a new page under Knowledge base

Add page about yaml validation

---

content/knowledge-base/Firebase Crashlytics dsym uploading

We've gotten many requests how to do this. Would be nice to document it

Create Firebase Crashlytics dsym uploading example

---

content/specs/versions-linux.md
content/specs/versions.md
content/specs/versions2.md
content/specs/versions3.md

Base image update @ 03-05-2021

Base image update @ 03-05-2021

---

content/flutter/flutter-projects.md
content/publishing/github-release.md
content/publishing/publish-release-notes.md
content/publishing/publishing-to-codemagic-static-pages.md
content/publishing/snap-store.md

- added info about build platforms and build machine types
- updated build instructions per build platform
- added info about building and publishing snap packages

Desktop workflows

---

content/specs/versions-linux.md
content/specs/versions.md
content/specs/versions2.md
content/specs/versions3.md

Base image update @ 04-05-2021

Base image update @ 04-05-2021

---

content/code-signing-yaml/signing-ios.md
content/getting-started/building-a-cordova-app.md
content/getting-started/building-a-flutter-app.md
content/getting-started/building-a-native-android-app.md
content/getting-started/building-a-native-ios-app.md
content/getting-started/building-a-react-native-app.md
content/getting-started/building-an-ionic-app.md
content/getting-started/building_a_native_app_with_flutter_module.md
content/troubleshooting/common-issues.md

Main changes:
* reordered pages based on perceived customer interest
* added cordova getting started guide
* simplified ionic guide while I was there

Add cordova getting started guide

---

content/code-signing/ios-code-signing.md

Update in relation to loading bundle IDs from Apple Developer Portal

Update bundle ID info

---

content/specs/versions.md
content/specs/versions2.md
content/specs/versions3.md

Base image update @ 12-05-2021

Base image update @ 12-05-2021

---

content/building/access-private-git-submodules.md

inspired by this conversation https://codemagicio.slack.com/archives/CEKE2KZ37/p1620910891382400

update info about private dependencies

---

content/getting-started/building-a-react-native-app.md
content/integrations/jira-integration.md

Updated link to jira integration demo project.

Jira integration updates

---

config.yml
content/getting-started/building-a-react-native-app.md
content/integrations/jira-integration.md
content/sample-projects/codemagic-sample-projects.md

Add a section in the documentation to make it easier to find the codemagic-sample-projects GitHub repository.

Sample projects

---

content/specs/versions-linux.md
content/specs/versions.md
content/specs/versions2.md
content/specs/versions3.md

Base image update @ 20-05-2021

Base image update @ 20-05-2021

---

content/building/build-versioning.md

Alternative to https://github.com/codemagic-ci-cd/codemagic-docs/pull/323

Clear up ambiguity with fetching build number and version from pubspec

---

content/specs/versions-linux.md
content/specs/versions.md
content/specs/versions2.md
content/specs/versions3.md

Base image update @ 31-05-2021

Base image update @ 31-05-2021

---

content/getting-started/adding-apps-from-custom-sources.md
content/getting-started/signup.md
content/knowledge-base/migrate-to-github-app.md

Covers the new flow for adding applications.
There are substantial changes in https://docs.codemagic.io/getting-started/adding-apps-from-custom-sources/ and https://docs.codemagic.io/getting-started/signup/.
Does not cover the changes related to Applications dashboard.
[do not merge before the feature is public]

New add app flow

---

content/knowledge-base/video-resources.md

Added a section in the KB that links to the Codemagic YouTube channel.

Add Knowledge Base entry for video resources

---

content/getting-started/yaml.md

This can be merged after the relevant changes have been deployed on Monday.

WIP - update documentation regarding Java versioning

---

content/specs/versions-linux.md

Base image update @ 15-06-2021

Base image update @ 15-06-2021

---

content/specs/versions-linux.md
content/specs/versions.md
content/specs/versions2.md
content/specs/versions3.md

Base image update @ 28-06-2021

Base image update @ 28-06-2021

---

content/specs/versions-linux.md
content/specs/versions.md
content/specs/versions2.md
content/specs/versions4.md

Base image update @ 01-07-2021

Base image update @ 01-07-2021

---

content/specs/versions-linux.md
content/specs/versions.md
content/specs/versions2.md
content/specs/versions3.md
content/specs/versions4.md

Base image update @ 05-07-2021

Base image update @ 05-07-2021

---

content/publishing/beta-deployment-with-fastlane.md
content/publishing/email-and-slack-notifications.md
content/publishing/firebase-app-distribution.md
content/publishing/github-release.md
content/publishing/publish-app-artifacts-to-app-center.md
content/publishing/publish-build-artifacts-to-amazon-s3.md
content/publishing/publish-release-notes.md
content/publishing/publishing-to-app-store.md
content/publishing/publishing-to-codemagic-static-pages.md
content/publishing/publishing-to-google-play.md
content/publishing/snap-store.md

Added a new page about setting up publishing to Firebase App Distribution in Flutter workflow editor

Add FAD workflow editor docs

---

content/specs/versions-linux.md
content/specs/versions.md
content/specs/versions2.md
content/specs/versions4.md

Base image update @ 19-07-2021

Base image update @ 19-07-2021

---

content/specs/versions4.md

Base image update @ 02-08-2021

Base image update @ 02-08-2021

---

content/specs/versions4.md

Base image update @ 12-08-2021

Base image update @ 12-08-2021

---

content/knowledge-base/beta-deployment-with-fastlane.md
content/knowledge-base/publish-app-artifacts-to-app-center.md
content/knowledge-base/publish-build-artifacts-to-amazon-s3.md

These articles will also be useful for YAML based configuration.
Made sure that URLs will not break

Improvement: move extra deployment options to Knowledge base

---

content/knowledge-base/publish-build-artifacts-to-amazon-s3.md

Update the doc about publishing artifacts to S3 with yaml instructions.

make instructions generic

---

content/billing/pricing.md

Add Free plan information and more detail about additional concurrencies for Teams

 Free plan information and additional concurrency details

---

content/specs/versions-linux.md
content/specs/versions.md
content/specs/versions2.md
content/specs/versions3.md
content/specs/versions4.md

Base image update @ 13-09-2021

Base image update @ 13-09-2021

---

content/variables/environment-variable-groups.md

Updating the examples for Android and iOS to have a better understanding on using groups. Eventually chaining all the sample projects.

Updating Environment variable groups

---

content/specs/versions4.md

Base image update @ 17-09-2021

Base image update @ 17-09-2021

---

content/yaml-quick-start/building-a-flutter-app.md

Fix: Flutter project - Env group variables

Fix: Flutter project - Env group variables

---

content/yaml/yaml-getting-started.md

Updated yaml - Env variable groups

Updated yaml - Env variable groups

---

content/variables/environment-variable-groups.md

Removed encrypting variables and added info for storing sensitive data

Fix: removal of encrypting variables

---

content/specs/versions-linux.md
content/specs/versions.md
content/specs/versions2.md
content/specs/versions3.md
content/specs/versions4.md

Base image update @ 19-09-2021

Base image update @ 19-09-2021

---

content/specs/versions.md
content/specs/versions2.md
content/specs/versions3.md

Base image update @ 20-09-2021

Base image update @ 20-09-2021

---

content/yaml-publishing/distribution.md

Remove an unnecessary sentence

remove extra sentence

---

content/flutter-publishing/firebase-app-distribution.md

https://codemagicio.slack.com/archives/CEKE2KZ37/p1632399999082700

Fix: role for Firebase distribution with service account

---

content/specs/versions-linux.md
content/specs/versions.md
content/specs/versions2.md
content/specs/versions3.md
content/specs/versions4.md

Base image update @ 04-10-2021

Base image update @ 04-10-2021

---

content/specs/versions4.md

Base image update @ 02-11-2021

Base image update @ 02-11-2021

---

content/specs/versions-windows.md

Base image update @ 16-11-2021

Base image update @ 16-11-2021

---

content/specs/versions4.md

Base image update @ 22-11-2021

Base image update @ 22-11-2021

---

content/specs/versions-linux.md
content/specs/versions-windows.md
content/specs/versions.md
content/specs/versions2.md
content/specs/versions3.md
content/specs/versions4-unity.md

Base image update @ 23-11-2021

Base image update @ 23-11-2021

---

content/integrations/fastlane-integration.md

added info to make sure to secure the variable. Otherwise it would have seemed that you paste the value and store it as plain text.

Update Fastlane integration docs

---

content/yaml-publishing/distribution.md

- Add example for publishing to App Store
- Split example for uploading the IPA, TestFlight configuration and App Store release

Add info about app store review

---

content/specs/versions-windows.md
content/specs/versions4-unity.md
content/yaml-quick-start/building-a-unity-app.md

Unity is installed via Unity Hub along with the relevant modules (see screenshot)

Improvement: install Unity

---

content/specs/versions4-unity.md

Base image update @ 06-12-2021

Base image update @ 06-12-2021

---

content/yaml-code-signing/signing-ios.md

Clarify when to use IOS_APP_STORE and IOS_APP_ADHOC when code signing

---

content/specs/versions-windows.md
content/specs/versions4-unity.md

Base image update @ 07-12-2021

Base image update @ 07-12-2021

---

content/specs/versions-windows.md
content/specs/versions4-unity.md

Base image update @ 08-12-2021

Base image update @ 08-12-2021

---

content/integrations/fastlane-integration.md

Show how to add Fastlane plugins

---

content/specs/versions-linux.md
content/specs/versions-windows.md
content/specs/versions.md
content/specs/versions2.md
content/specs/versions3.md
content/specs/versions4-unity.md
content/specs/versions4.md

Base image update @ 13-12-2021

Base image update @ 13-12-2021

---

content/yaml-publishing/publish-release-notes.md

Add information about including localized App Store version meta information when submitting build to App Store review.

Update release notes docs

---

content/yaml-quick-start/building-a-flutter-app.md

* Fixed the path before zipping windows files
* Fixed the link to Microsoft Docs

Windows build fixes

---

content/specs/versions-linux.md
content/specs/versions-windows.md
content/specs/versions.md
content/specs/versions2.md
content/specs/versions3.md
content/specs/versions4-unity.md
content/specs/versions4.md

Base image update @ 20-12-2021

Base image update @ 20-12-2021

---

content/specs/versions-windows.md
content/specs/versions4-unity.md

Base image update @ 21-12-2021

Base image update @ 21-12-2021

---

content/specs/versions4.md

Base image update @ 23-12-2021

Base image update @ 23-12-2021

---

content/getting-started/firewall.md
content/troubleshooting/accessing-builder-machine-via-ssh.md

open for discussion re wording

Windows specific updates to docs

---

content/getting-started/projects.md
content/specs/machine-type.md

- Updated the project types with Unity and Windows (Flutter)
- Updated Xcode update policy with recent Xcocde versions

Add missing platforms

---

content/yaml-quick-start/building-a-unity-app.md

Make variable names consistent

---

content/specs/versions-linux.md
content/specs/versions4.md

Base image update @ 20-01-2022

Base image update @ 20-01-2022

---

content/billing/billing.md

Instead of the invoice icon, there are now buttons to view and pay invoices.

New buttons to view and pay invoices

---

content/specs/machine-type.md
content/specs/versions-linux.md
content/specs/versions-macos-xcode-11.md
content/specs/versions-macos-xcode-12-0.md
content/specs/versions-macos-xcode-12-5.md
content/specs/versions-macos-xcode-13-0-unity.md
content/specs/versions-macos-xcode-13-0.md
content/specs/versions-macos-xcode-13-3.md
content/specs/versions-windows.md

Base image update @ 02-02-2022

Base image update @ 02-02-2022

---

content/specs/versions-linux.md
content/specs/versions-macos-xcode-11.md
content/specs/versions-macos-xcode-12-0.md
content/specs/versions-macos-xcode-12-5.md
content/specs/versions-macos-xcode-13-0-unity.md
content/specs/versions-macos-xcode-13-0.md
content/specs/versions-macos-xcode-13-3.md
content/specs/versions-windows.md

Base image update @ 04-02-2022

Base image update @ 04-02-2022

---

content/specs/versions-macos-xcode-13-3.md

Base image update @ 11-02-2022

Base image update @ 11-02-2022

---

content/specs/versions-linux.md
content/specs/versions-macos-xcode-11.md
content/specs/versions-macos-xcode-12-0.md
content/specs/versions-macos-xcode-12-5.md
content/specs/versions-macos-xcode-13-0-unity.md
content/specs/versions-macos-xcode-13-0.md
content/specs/versions-macos-xcode-13-3.md
content/specs/versions-windows.md

Base image update @ 12-02-2022

Base image update @ 12-02-2022

---

content/specs/versions-windows.md

Base image update @ 15-02-2022

Base image update @ 15-02-2022

---

content/specs/versions-macos-xcode-11.md
content/specs/versions-macos-xcode-12-0.md
content/specs/versions-macos-xcode-12-5.md
content/specs/versions-macos-xcode-13-0.md
content/specs/versions-macos-xcode-13-3.md
content/specs/versions-windows.md

Base image update @ 22-02-2022

Base image update @ 22-02-2022

---

content/specs/versions-macos-xcode-13-3.md

Base image update @ 25-02-2022

Base image update @ 25-02-2022

---

content/specs/versions-linux.md

Base image update @ 03-03-2022

Base image update @ 03-03-2022

---

content/specs/versions-linux.md
content/specs/versions-macos-xcode-11.md
content/specs/versions-macos-xcode-12-0.md
content/specs/versions-macos-xcode-12-5.md
content/specs/versions-macos-xcode-13-0.md
content/specs/versions-macos-xcode-13-3.md
content/specs/versions-windows.md

Base image update @ 04-03-2022

Base image update @ 04-03-2022

---

content/specs/versions-macos-xcode-13-3.md

Base image update @ 11-03-2022

Base image update @ 11-03-2022

---

content/specs/versions-macos-xcode-13-3.md

Base image update @ 21-03-2022

Base image update @ 21-03-2022

---

content/billing/pricing.md

line 34 should be fixed I guess

Adding windows VM pricing info

---

content/specs/versions-macos-xcode-13-0.md
content/specs/versions-macos-xcode-13-3.md

Base image update @ 27-03-2022

Base image update @ 27-03-2022

---

content/specs/versions-linux.md
content/specs/versions-macos-xcode-11.md
content/specs/versions-macos-xcode-12-0.md
content/specs/versions-macos-xcode-12-5.md
content/specs/versions-macos-xcode-13-0.md
content/specs/versions-macos-xcode-13-3.md
content/specs/versions-windows.md

Base image update @ 29-03-2022

Base image update @ 29-03-2022

---

content/specs/versions-macos-m1-xcode-13-3.md

Base image update @ 06-04-2022

Base image update @ 06-04-2022

---

content/specs/machine-type.md
content/yaml/yaml-getting-started.md

- Update the table of instance types for Yaml
- Update the doc about build machine types

Add info about M1 instance type

---

content/specs/versions-macos-xcode-13-3.md

Base image update @ 18-04-2022

Base image update @ 18-04-2022

---

content/specs/versions-linux.md
content/specs/versions-macos-m1-xcode-13-3.md
content/specs/versions-macos-xcode-11.md
content/specs/versions-macos-xcode-12-0.md
content/specs/versions-macos-xcode-12-5.md
content/specs/versions-macos-xcode-13-0.md
content/specs/versions-macos-xcode-13-3.md
content/specs/versions-windows.md

Base image update @ 20-04-2022

Base image update @ 20-04-2022

---

content/troubleshooting/accessing-builder-machine-via-ssh.md
content/troubleshooting/codemagic-status-page.md
content/troubleshooting/common-android-issues.md
content/troubleshooting/common-google-play-errors.md
content/troubleshooting/common-ios-issues.md

Formatting and editing

---

content/specs/versions-linux.md
content/specs/versions-macos-m1-xcode-13-3.md
content/specs/versions-macos-xcode-13-0.md
content/specs/versions-macos-xcode-13-3.md
content/specs/versions-windows.md

Base image update @ 17-05-2022

Base image update @ 17-05-2022

---

content/specs/versions-linux.md
content/specs/versions-macos-m1-xcode-13-3.md
content/specs/versions-macos-xcode-13-0.md
content/specs/versions-macos-xcode-13-3.md
content/specs/versions-windows.md

Base image update @ 22-05-2022

Base image update @ 22-05-2022

---

content/specs/versions-macos-m1-xcode-13-3.md

Base image update @ 27-05-2022

Base image update @ 27-05-2022

---

content/specs/versions-macos-m1-xcode-13-3.md
content/specs/versions-macos-xcode-13-3.md

Base image update @ 30-05-2022

Base image update @ 30-05-2022

---

content/specs/versions-macos-m1-xcode-13-3.md
content/specs/versions-macos-xcode-13-3.md

Base image update @ 05-06-2022

Base image update @ 05-06-2022

---

content/yaml-quick-start/building-a-native-android-app.md

in the Set up Keystore script step

removed android folder from the path

---

content/specs/versions-linux.md
content/specs/versions-macos-m1-xcode-13-3.md
content/specs/versions-macos-xcode-13-0.md
content/specs/versions-macos-xcode-13-3.md
content/specs/versions-windows.md

Base image update @ 12-06-2022

Base image update @ 12-06-2022

---

content/yaml-quick-start/building-a-react-native-app.md

Updated Sample project Link, was incorrect - 404.

Document update

---

content/yaml-testing/testing.md

currently, I have updated the doc for Flutter, I will take it up for Native iOS as well.

working with specific iOS Simulator

---

content/specs/versions-macos-m1-xcode-13-3.md
content/specs/versions-macos-xcode-13-0.md
content/specs/versions-macos-xcode-13-3.md

Base image update @ 27-06-2022

Base image update @ 27-06-2022

---

content/billing/pricing.md

Updated info about build history and artifacts retention to reflect upcoming changes.

Update build history retention policy

---

content/yaml-quick-start/building-a-react-native-app.md

Requires the "markdown" shortcode PR to be accepted first

Complete rewrite of the React Native Quiick Start

---

content/yaml-publishing/publish-release-notes.md

Add a warning about unsupported symbols in release notes (from Issue #803)

Add a warning

---

content/specs/versions-linux.md
content/specs/versions-macos-m1-xcode-13-3.md
content/specs/versions-macos-xcode-13-0.md
content/specs/versions-macos-xcode-13-3.md
content/specs/versions-windows.md

Base image update @ 05-07-2022

Base image update @ 05-07-2022

---

content/specs/versions-linux.md
content/specs/versions-macos-m1-xcode-13-3.md
content/specs/versions-macos-xcode-13-0.md
content/specs/versions-macos-xcode-13-3.md
content/specs/versions-windows.md

Base image update @ 16-07-2022

Base image update @ 16-07-2022

---

content/specs/versions-linux.md
content/specs/versions-macos-xcode-13-0.md
content/specs/versions-macos-xcode-13-3.md

Base image update @ 21-07-2022

Base image update @ 21-07-2022

---

content/yaml-quick-start/building-a-flutter-app.md

There was no need for cd . && commands

remove cd commands

---

content/specs/versions-macos-m1-xcode-13-3.md
content/specs/versions-macos-xcode-13-3.md

Base image update @ 06-08-2022

Base image update @ 06-08-2022

---

content/specs/versions-macos-m1-xcode-13-3.md

Base image update @ 12-08-2022

Base image update @ 12-08-2022

---

content/specs/versions-macos-xcode-13-3.md

Base image update @ 15-08-2022

Base image update @ 15-08-2022

---

content/flutter-configuration/flutter-projects.md
content/integrations/pcloudy-integration.md
content/partials/add-app-to-codemagic.md
content/teams/teams.md
content/yaml-publishing/aws.md
content/yaml-quick-start/building-a-flutter-app.md
content/yaml-quick-start/building-a-native-android-app.md
content/yaml-quick-start/building-a-react-native-app.md
content/yaml-quick-start/building-an-ionic-app.md

Fixed a bunch of broken links all around.

Fix broken links

---

content/partials/code-signing-ios-configure-environment-vars.md
content/partials/code-signing-ios.md

Reorganized the text a bit to improve clarity.

Code signing improvements

---

content/specs/versions-macos-m1-xcode-13-3.md
content/specs/versions-macos-xcode-13-3.md

Base image update @ 29-08-2022

Base image update @ 29-08-2022

---

content/yaml-publishing/google-play.md

I realized that there are some comments which is missing `.`. This PR adds it.

Add missing dots to Google Play Android page

---

content/specs/versions-linux.md
content/specs/versions-macos-m1-xcode-13-3.md
content/specs/versions-macos-xcode-13-0.md
content/specs/versions-macos-xcode-13-3.md
content/specs/versions-windows.md

Base image update @ 05-09-2022

Base image update @ 05-09-2022

---

content/specs/versions-linux.md
content/specs/versions-windows.md

Base image update @ 07-09-2022

Base image update @ 07-09-2022

---

content/yaml/yaml-getting-started.md

labels support docs update

---

content/billing/pricing.md

Corrections

---

content/specs/versions-linux.md
content/specs/versions-macos-m1-xcode-13-3.md
content/specs/versions-macos-xcode-13-0.md
content/specs/versions-macos-xcode-13-3.md
content/specs/versions-windows.md

Base image update @ 16-09-2022

Base image update @ 16-09-2022

---

content/specs/versions-macos-m1-xcode-13-3.md
content/specs/versions-macos-xcode-13-3.md

Base image update @ 26-09-2022

Base image update @ 26-09-2022

---

content/partials/specs/versions-macos-m1-xcode-13-3.md
content/partials/specs/versions-macos-xcode-11.md
content/partials/specs/versions-macos-xcode-12-0.md
content/partials/specs/versions-macos-xcode-12-5.md
content/partials/specs/versions-macos-xcode-13-0.md
content/partials/specs/versions-macos-xcode-13-3.md
content/specs/versions-linux.md
content/specs/versions-windows.md

Base image update @ 03-10-2022

Base image update @ 03-10-2022

---

content/yaml-quick-start/building-a-flutter-app.md

BUILD_NUMBER was not incremented, but the latest one was used which results in an error.

Fix increment of BUILD_NUMBER

---

content/partials/specs/versions-macos-m1-xcode-13-3.md
content/partials/specs/versions-macos-xcode-12-5.md
content/partials/specs/versions-macos-xcode-13-0.md
content/partials/specs/versions-macos-xcode-13-3.md
content/specs/versions-linux.md
content/specs/versions-windows.md

Base image update @ 14-10-2022

Base image update @ 14-10-2022

---

content/partials/specs/versions-macos-m1-xcode-13-3.md
content/partials/specs/versions-macos-xcode-12-5.md
content/partials/specs/versions-macos-xcode-13-0.md
content/partials/specs/versions-macos-xcode-13-3.md
content/specs/versions-linux.md
content/specs/versions-windows.md

Base image update @ 30-10-2022

Base image update @ 30-10-2022

---

content/partials/specs/versions-macos-m1-xcode-13-3.md
content/partials/specs/versions-macos-xcode-12-0.md
content/partials/specs/versions-macos-xcode-13-0.md
content/partials/specs/versions-macos-xcode-13-3.md
content/specs/versions-linux.md
content/specs/versions-windows.md

Base image update @ 07-11-2022

Base image update @ 07-11-2022

---

content/troubleshooting/accessing-builder-machine-via-ssh.md

Remote access is now only available when requested

Feature: optional remote access

---

content/knowledge-others/install-unity-version.md

Static resources should not be cached.

Remove recommendation to cache Unity version

---

content/partials/specs/versions-macos-m1-xcode-13-3.md
content/partials/specs/versions-macos-xcode-13-0.md
content/partials/specs/versions-macos-xcode-13-3.md
content/specs/versions-linux.md
content/specs/versions-windows.md

Base image update @ 28-11-2022

Base image update @ 28-11-2022

---

content/partials/specs/versions-macos-m1-xcode-13-3.md
content/partials/specs/versions-macos-m1-xcode-14-2.md
content/partials/specs/versions-macos-xcode-13-3.md
content/partials/specs/versions-macos-xcode-14-2.md
content/specs/versions-macos.md

Base image update @ 14-12-2022

Base image update @ 14-12-2022

---

content/partials/quickstart/add-app-to-codemagic.md

Just saw this small typo :) Nice documentation overall!

Fix typo in "Adding the app to Codemagic"

---

content/knowledge-codemagic/machine-type.md
content/specs/xcode-update-policy.md

Update the Xcode update policy and make it a separate page.

Add xcode update policy page

---

content/flutter-running-builds/starting-builds-automatically.md
content/yaml-running-builds/starting-builds-automatically.md

Replace default fnmatch with fnmatch from wcmatch library.
https://facelessuser.github.io/wcmatch/fnmatch/

Feature: wcmatch for automatic build triggering

---

content/billing/pricing.md

Add details about dedicated host pricing when using the Enterprise plan.

Enterprise plan with dedicated hosts

---

content/billing/pricing.md

Match the terminology used in the docs with the pricing page on the website.

Change In-app support to Chat support

---

content/rest-api/artifacts.md

[Discussion](https://nevercode.slack.com/archives/CCGU5M8P3/p1675340231206539?thread_ts=1675265969.090359&cid=CCGU5M8P3)

Feature: artifact download API

---

content/rest-api/artifacts.md

- Use steps
- change `:uuid1/:uuid2` to `:securePath`
- change example path to `/artifacts/securepath/myapp.ipa/`
- use `-X POST` in request example

Add steps, and update example syntax

---

content/billing/billing.md

Changed link to the 2023 certificate.

Update UTR certificate link

---

content/yaml-publishing/publishing-to-codemagic-static-pages.md

document CM static pages not supported with YAML

---

content/yaml-code-signing/signing-android.md

caught it while browsing docs 👍🏻

fix typo on android app signing page

---

content/specs/versions-macos.md

Specify that the M1 14.2 image has more versions available.

Update image name

---

content/knowledge-white-label/white-label-scripts.md

Question from Slack community said:
In the docs, you recommend to use the sed tool. But I'm not sure of all the places that need changing. It would be great if you can include a section in the docs with specific instructions on how to change bundle/application IDs. 
the answer is here: https://github.com/codemagic-ci-cd/white-label-demo-project so I thought to just add this info to the top of this page so people can self-serve.

Update white-label scripts

---

content/billing/billing.md

we got email about user asking how to update taxID and turns out it's not available on personal accounts. Updating docs to reflect that.

update billing info

---

content/yaml-code-signing/ios-simulator-builds.md

Makes it easier to copy paste from the documentation.

Update iOS simulator builds with latest iOS version

---

content/rest-api/teams.md

fix /team in endpoint as discussed here: https://nevercode.slack.com/archives/CCGU5M8P3/p1683105202171029

fix /team endpoint

---

content/knowledge-git/add-a-git-tag-with-app-version.md

Fix a typo in the example

---

content/yaml-quick-start/building-a-flutter-app.md

I also changed the numbering on the rest of the lines.

Updated the link to the guide for setting up service account

---

content/knowledge-codemagic/build-versioning.md

Documentation for a new new [firebase-app-distribution](https://github.com/codemagic-ci-cd/cli-tools/tree/master/docs/firebase-app-distribution) tool.
Document [get-latest-build-version](https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/firebase-app-distribution/get-latest-build-version.md#get-latest-build-version) action to get the last build version and how it can be used to improve Firebase workflows.

Feature: Firebase latest build version

---

content/troubleshooting/common-android-issues.md
content/yaml-publishing/firebase-app-distribution.md

Firebase app distribution updates

Firebase info update2

---

content/yaml-quick-start/white-label-getting-started.md

- Replace the script to change the Android package name.
- Mention the Flutter package to generate icons.

Wl guide improve

---

content/flutter-publishing/publishing-to-google-play.md
content/yaml-publishing/google-play.md

added information on how to publish to Wear Os Only tracks

publishing to wear OS only tracks

---

layouts/_default/head.html

all icons have been replaced, the link was left by accident

remove link to font awesome

---

content/partials/quickstart/build-versioning-ios.md
content/yaml-quick-start/building-a-dotnet-maui-app.md
content/yaml-quick-start/building-a-flutter-app.md
content/yaml-quick-start/building-a-kmm-app.md
content/yaml-quick-start/building-a-native-ios-app.md
content/yaml-quick-start/building-a-react-native-app.md
content/yaml-quick-start/building-a-unity-app.md
content/yaml-quick-start/building-an-ionic-app.md
static/codemagic-yaml-cheatsheet.html

changes from APP_ID  to APP_STORE_APPLE_ID

apple id var change

---

content/partials/code-signing-macos.md
content/partials/quickstart/code-signing-macos.md

Changed the certificate type name for the private key that needs to be exported

Mac App Distribution

---

content/troubleshooting/common-issues.md

Added information to common issues on how to change an added applications repository URL.

1906 information about changing applications repo

---

content/rest-api/applications.md
content/rest-api/builds.md

Added this note to 2 yaml api pages.
{{}} **Note:** Using our API you cannot fetch information about workflows when configuring with **codemagic.yaml**, as we do not save YAML configurations to our database. Values regarding workflows will be null or false. {{}}

1949 api information about yaml

---

content/yaml-quick-start/building-a-react-native-app.md

Updated Expo project initialization - removed information about Expo CLI global, as expo tools now come within Node LTS, no need for further installation.

Updated Expo project initialization

---

content/partials/specs/versions-macos-intel-xcode-12-5.md
content/partials/specs/versions-macos-intel-xcode-13-0.md
content/partials/specs/versions-macos-intel-xcode-13-3.md
content/partials/specs/versions-macos-intel-xcode-14-2.md

Remove Mac mini machine specs following deprecation.

Improvement: deprecate Mac mini

---

content/yaml-code-signing/ios-simulator-builds.md

added an example for creating an unsigned .net7 maui app

Build the app for iOS Simulator

---

content/troubleshooting/common-google-play-errors.md
content/yaml-publishing/google-play.md

moved steps that are related to troublshoting

---

content/knowledge-codemagic/caching.md

Sync caching docs with upcoming changes.

Update caching docs

---

content/yaml-notification/publish-release-notes.md

generating release notes with git commits

---

content/knowledge-others/install-unity-version.md

Adding support to Unity Editor `2021.3.28f1`

Support Unity editor `2021.3.28f1`

---

content/knowledge-others/install-unity-version.md

Added these new Unity versions:
- `2022.3.10f1`
- `2022.3.11f1`
- `2022.3.7f1`
- `2023.1.10f1`
- `2023.1.17f1`

Add more Unity versions

---

content/flutter-publishing/publishing-to-google-play.md
content/yaml-publishing/google-play.md

Google play console dashboard changes implemented for wfe and minor typo for yaml section.

wfe play publishing

---

content/yaml-basic-configuration/yaml-getting-started.md
content/yaml-running-builds/starting-builds-automatically.md

Mention that the new `pull_request_labeled` event is only for GitHub repos.

Add new `pull_request_labeled` triggering event

---

content/yaml-quick-start/building-a-native-android-app.md

fixed path

---

content/notes/release-notes.md

Update release notes

---

content/flutter-notification/publish-release-notes.md
content/yaml-notification/publish-release-notes.md

Info regarding the primary locale
Reference on slack [here](https://nevercode.slack.com/archives/CCGU5M8P3/p1701438555254479?thread_ts=1700727394.084039&cid=CCGU5M8P3).

release-notes-updates

---

content/flutter-publishing/publishing-to-google-play.md
content/yaml-publishing/google-play.md

There is an update which requires developers to select the release section.
Reference: #2209
I have verified this at my end.

play-store changes

---

content/notes/release-notes.md

Add release notes for Xcode 15.2 Beta 1.

15.2 Beta 1

---

content/knowledge-white-label/white-label-apps-overview.md
content/yaml-quick-start/building-a-unity-app.md

- added a missing link
- updated the title in the unity guide

changed link and updated title

---

content/notes/release-notes.md

Update release notes with Xcode 15.2 release

Add info about Xcode 15.2 release

---

content/yaml-quick-start/building-a-react-native-app.md

Expo eject already deprecated
https://docs.expo.dev/faq/#is-expo-eject-deprecated

change expo eject to npx expo prebuild

---

content/partials/quickstart/build-versioning-kmm-android.md
content/partials/quickstart/code-signing-kmm-android.md
content/yaml-quick-start/building-a-kmm-app.md

kmm guide fix and improvements

---

content/knowledge-others/install-unity-version.md

added unity version `2022.3.19f1`

updated unity version list

---

content/troubleshooting/common-ios-issues.md

Solution for _Did not find xcodeproj from /Users/builder/clone/ios_ error

Did not find xcodeproj

---

content/troubleshooting/codemagic-status-page.md

Update docs with Codemagic status page link

Link to status page

---

content/partials/firewall.md

- add Las Vegas
- improve description and formatting (now it's possible to copy all addresses to clipboard)
- TBD new Atlanta

update firewall requirements

---

content/getting-started/about-codemagic.md

We are missing the information in the documentation regarding where to go in order to subscribe to a newsletter

adde the newsletter info

---

content/notes/release-notes.md

- Add updates about Xcode 15.4 image
- Add a note about App Store phased releases

Xcode version updates and phased releases

---

content/specs/xcode-update-policy.md

Updated the page to mention that our policy is guided by Apple's requirements.

Update Xcode update and deprecation policy

---

content/specs/versions-macos.md

fixes tab for Xcode 16 points to the wrong file

add tab for xcode 16

---

content/yaml-basic-configuration/yaml-getting-started.md

Fix the link attached to “here” under the Build Inputs section at https://docs.codemagic.io/yaml-basic-configuration/yaml-getting-started/#build-inputs

fix broken link

---

assets/js/search.js

update const updateFromUrl with URLSearchParams

update const updateFromUrl with URLSearchParams

---

content/partials/firewall.md

Fix: copy button for IP addresses

---

content/knowledge-others/partner-center-authentication.md

the link to the Azure Portal has changed

update azure link

---

content/yaml-basic-configuration/environment-variables.md

Add the new builtin variables for triggering events `CM_TRIGGER_SOURCE` and `CM_BUILD_STARTED_BY`.

Add new builtin environment variables for triggering events

---

content/knowledge-others/binary-names-update.md

add an example of renaming the .aab file

add an example of renaming the .aab file

---

content/yaml-code-signing/signing-macos.md

fix TOC for Signing macOS apps page

add full text instead include

---

content/yaml-publishing/tester-groups.md

Add documentation for the tester groups feature.

Add docs for tester groups

---

content/knowledge-others/install-unity-version.md

update list of pre-cached Unity versions

update Unity versions

---

content/yaml-notification/telegram.md

Telegram notification

---

content/partials/app-preview-builds.md

Specify that the app preview feature is available to teams on request.

Update info about app preview availability

---

content/yaml-basic-configuration/configuring-environment-variables.md

This PR specifies that global variables and secrets are only available for teams.

Update info about global variables availability

---

content/yaml-running-builds/starting-builds-automatically.md

Add an example on how to access the built in env variable and use it within the condition

access built in env variable within condition

---

content/troubleshooting/common-ios-issues.md

* Add a link to the Apple Developer account profiles page
* Improve the wording

Add a link to the Apple Developer account profiles page

---

content/yaml-quick-start/building-a-flutter-app.md

Update the Flutter packages script from `flutter packages pub get` to `flutter pub get`

Fix the "Get Flutter packages" script

---

.github/workflows/deploy.yml
config.yaml
layouts/partials/opengraph.html
layouts/partials/twitter_cards.html
readme.md

bump Hugo version

---

content/billing/pricing.md

Access to more powerful macOS machines

M2 Studio and Ultra machines

---

content/troubleshooting/common-android-issues.md

* Remove M2 Pro
* Correct M2 Max name

Remove M2 Pro

---

content/yaml-quick-start/codemagic-sample-projects.md

* Redirecting to sample projects
* Moved it to the integrations section

Updating Firebase App Distribution Sample Project

---

content/flutter-publishing/publishing-to-app-store.md
content/partials/quickstart/code-signing-ios-reference-certificate.md
content/partials/yaml-publishing-app-store-connect-environment-variables.md
content/partials/yaml-publishing-app-store-connect-team-integration.md
content/yaml-code-signing/signing-ios.md

Fixes https://github.com/codemagic-ci-cd/codemagic-docs/issues/2890

Add guide to publish to Testflight internal testing only

---

content/yaml-publishing/google-play.md

Add the new Google Play field `release_name`

Google Play release name field

---

assets/js/main.js

Remove analytics events sent to our backend that are not longer supported.

Remove Analytics Events

---

content/billing/pricing.md

* Replacing M2 with M4 for base plan
* Adding an option with M4 Pro machines

Enterprise plan update

---

content/knowledge-others/install-unity-version.md

Add flags for prompt during download and install from Unity Hub macOS

---

content/billing/pricing.md

Add title to section and minor update to wording.

CodePush pricing section

---

content/partials/app-preview-builds.md

Review the documentation for app preview feature.

Improvement: review app preview page

---

content/flutter-publishing/firebase-app-distribution.md
content/flutter-publishing/github-releases.md
content/flutter-publishing/publishing-to-aws.md
content/flutter-publishing/publishing-to-codemagic-static-pages.md
content/flutter-publishing/shorebird.md
content/flutter-publishing/snap-store.md

Add a new page about configuring Shorebird workflows in Flutter workflow editor.

Add documentation about Shorebird

---

content/flutter-publishing/shorebird.md

Update Shorebird docs

---

content/yaml-quick-start/building-a-unity-app.md

Our Unity [samples](https://docs.codemagic.io/yaml-quick-start/building-a-unity-app/#conclusion) were missing the required unty version

added missing unity versions in unity samples

---

content/integrations/codepush-integration.md

Single CodePush server

---

content/billing/pricing.md
content/flutter-testing/app-preview.md
content/integrations/codepush-integration.md
content/knowledge-codemagic/machine-type.md
content/knowledge-others/install-unity-version.md
content/troubleshooting/common-android-issues.md
content/yaml-testing/app-preview.md

unify links to separate support and pricing questions

review links

---

content/yaml-basic-configuration/configuring-environment-variables.md

Restructure the page describing adding environment variables to improve readability and fascilitate finding important information.

Restructure environment variable docs

---

content/billing/pricing.md

Removing free CodePush option for Enterprise

CodePush Enterprise pricing

---

content/flutter-testing/app-preview.md
content/yaml-testing/app-preview.md

PAYG teams can now enable App Preview via Codemagic UI.

Add info about enabling App Preview

---

content/troubleshooting/help-and-support.md

Chat Widget

---

content/flutter-testing/app-preview.md
content/yaml-testing/app-preview.md

- Fix cross-references between yaml and workflow editor docs
- mention Stellar to make it easier to find the docs

Update App Preview docs

---

content/flutter-testing/app-preview.md
content/yaml-testing/app-preview.md

- Add a yaml sample that works with native iOS apps
- Simplify Flutter yaml sample
- Link to Stellar video
- Mention trial info

Update App Preview info

---

content/integrations/codepush-integration.md

* Removing Microsoft CodePush CLI instances
* Adding Codemagic CodePush CLI tools

Codemagic CodePush CLI tools

---

content/yaml-quick-start/white-label-getting-started.md

* Updating API for uploading environment variables in bulk

Bulk uploading env vars to team settings

---

content/integrations/codepush-integration.md

Remove code-push-standalone in favor of code-push

Updating CodePush CLI

---

content/yaml-notification/github-checks.md

Support re-running failed GitHub checks.

Support re-running GitHub checks

---

content/integrations/codepush-integration.md

- Add step to show how plugin is used within the React Native app.
- Formatting updates.

Add step to show CodePush plugin use within a React Native app. 

---

content/yaml-testing/detox-testing.md

What is Detox and how to automate E2E testing

Detox (E2E) test automation
