content/building/yaml.md

We encode yaml-encrypted file to base64. This was missing from docs.

Clarify that yaml-encrypted file is base64

---

content/releases-and-versions/versions.md

- added Mac Mini and Mac Pro specification
- added system version and disk usage info
- dart & flutter moved to other tools, added more system tools
- separate section for default Xcode with runtimes and devices

new base image report template

---

content/building/automatic-build-triggering.md

After speaking with Slack support about triggering builds via the REST API when using YAML Advanced Configuration, I was given information not provided in the documentation. I added the specifications for making REST API calls to trigger build using YAML configuration by highlighting the use of "fileWorkflowId" rather than "workflowId" and where to get your fileWorkflowId from the YAML file.

Add Documentation For Custom Build Triggers with YAML Configuration

---

content/custom-scripts/add-a-git-tag-with-app-version.md

The git command contains twice "your-username" but you need the username only at the beginning.

Correction for git command

---

assets/js/search.js

Added fuzziness parameter equal to 1
[Fuzzy matches](https://lunrjs.com/guides/searching.html#fuzzy-matches)
✅ search picks up names with dots, like `.p12` and `.mobileprovision`
✅ search works as expected for other queries
✅ search for queries with two leading dots, like `.something .some-something`

Search works for query with a dot

---

content/building/yaml.md

There has been some confusion about the CERTIFICATE_PRIVATE_KEY variable in automatic code signing with .yaml file. Users didn't know where to find it or what key we are looking for. Included a tutorial from Github how to create it.

Update yaml.md with CERTIFICATE_PRIVATE_KEY tutorial link for iOS automatic code signing

---

content/testing/beta-testing-with-testmagic.md

People ask for the Testmagic link in Slack because of this part in the documentation. - added link to testflight here so they don't have to go to Slack and keep Slack channel for discussions.

Update Testmagic iOS link in docs.

---

content/custom-scripts/load-firebase-configuration.md

Not all the users know that $FCI_BUILD_DIR is the folder with repo content, not the folder containing the repo folder.
Next changes will make it less ambiguous, because at least one user had hard time trying to specify it as `PROJECT_ROOT=$FCI_BUILD_DIR/<repository_name>`

explain project path to load firebase config

---

content/rest-api/builds.md

POST /builds is done async and won't return result. Instead a user should find the started build from /builds endpoint.

Fix api /builds POST docs 

---

content/yaml/building-a-native-android-app.md
content/yaml/building-a-native-ios-app.md

**Description**
While by default when it comes to Native iOS and Native Android, we are actually in the right directory to execute the following commands, we still decided to change the code snippets a bit.
Due to the fact that we get many questions that could be avoided when people understood that changing directories and running the command should be done under the same script, we discussed with Mikhail that it could help if multiline scripts and changing directories would also be visible in places where users might see them better.
Using $FCI_BUILD_DIR also indicates to new users that we have environment variables that they can use to make their experience easier.
**Possible to-do's**
- make similar changes to elsewhere in the documentation
- find a place where to explain that each …

Update Native iOS and Native Android documentation for clarity

---

content/building/building-android-app-bundles.md
content/code-signing/android-code-signing.md
content/publishing/publishing-to-google-play.md
content/yaml/building-a-flutter-app.md
content/yaml/runninglocally.md

There was an error, `build-universal-apk` has the option `--bundle`, not `--pattern` (that was changed).
Also would like to mention about possibilities to use glob patterns with cli tools.
Multiples apks can be generated if there are different .aab (matched by pattern), so better make plural.
Using no quotes or double quotes leads to some edge case complications, so it's better just to ask to use single quotes.

Fix build-universal-apk usage

---

content/code-signing/android-code-signing.md

**Description**
The purpose of this PR is to update Codemagic's documentation in regard to Android code signing as some of the steps for the second option were either outdated or misleading.
As both options use build.gradle to sign, the title for option 1 was also modified to avoid confusion.
In addition as .keystore and .jks are both valid for keystore files and similar samples in Flutter documentation and our blog posts both use .jks format, I changed it here as well to have it the same everywhere.

update android code signing documentation

---

content/getting-started/setting-up.md

Searching for "can you add Codemagic with read only access" or similar results in Codemagic requires read/write permission to build your app." let's fix this by clarifying that Codemagic OAuth app requires read/write access, but GitHub app and adding projects via SSH requires read only access. 
I haven't checked what the layout looks like, please review

Updating Codemagic permission for adding projects

---

content/building/custom-scripts.md

Some users thought that if they have project file path specified, custom scripts will also be run from it. But it's not the case, custom scripts are always run from root.

say to change custom script dir

---

content/code-signing/android-code-signing.md

**Description**
During the last PR to change the Android code signing documentation, one minor detail was overlooked, as the file now generated is keystore_name.jks not keystore_name.keystore.

change .keystore to .jks

---

content/yaml/testing.md

We now support an expanded form for `script` entries in codemagic.yaml. Adding a little example to the tests page.
Also I couldn't help but notice the "instrumental tests" mention in the same file. I believe "instrumented tests" is the correct term for app development.

Document YAML test report

---

content/building/building-android-app-bundles.md

We now allow you choose between three ways to build Android projects: APK (default, same as before), AAB with universal APK (same as before when "build AAB" was checked), and just AAB (new). Consequently, there is now a dropdown with three choices instead of a checkbox.
Preferred option is the new one - AAB as it skips generating the universal APK, therefore speeding up the build.

Add comment about new aab selection

---

content/publishing/publish-release-notes.md

I'm not sure if 
```
* Release notes with `en-US` language code will be published to Email, Slack and GitHub releases in case file with `en-US` language code exists. If not, the first release notes will be published.
* To Google Play all the found release notes will be published with corresponding language codes.
```
is a correct way to form sentences here. Do I need to rephrase it?

added multiple languages

---

assets/scss/main.scss

It's visually difficult to understand the hierarchy of sections in documentation, especially when it comes to h2 and h3.
Use the same heading styles in documentation as in the [blog](https://blog.codemagic.io/).

change font sizes according to the font sizes in blog

---

content/getting-started/adding-apps-from-custom-sources.md

during the last major celery failure we recreated the GCP instance which lead to the change of IP address
NB: I wonder whether we need to send a notification to users about this change as those who already have the old IP in their firewalls may now experience connectivity issues.

update backend ip address

---

content/troubleshooting/common-issues.md

```
:x:  error: Runner has conflicting provisioning settings. Runner is automatically signed, but code signing identity Apple Push Services has been manually specified. Set the code signing identity value to "iPhone Developer" in the build settings editor, or switch to manual signing in the Signing & Capabilities editor. (in target 'Runner' from project 'Runner')
```
The above error usually occurs when users do not have their bundle identifiers correctly set in Xcode, or when their bundle identifier does not match the one set in the UI.
Not a 100% sure about the formating, but there was a previous issue with provisioning profile already there, so I put them under the same headline.
Related to this:
https://github.com/NevercodeHQ/codemagic-support/issues/76

Update common issues with provisioning profile error

---

content/yaml/building-a-native-ios-app.md

Publishing password may be misleading as appleID password, but in fact it is not - we require an app specific password associated with the apple ID instead.

update publishing description

---

content/yaml/distribution.md

User reported that the provided ssh-keygen command did not work for their certificates. This is because it generates an "OPENSSH" private key by default with newer versions of Mac OS.
Update command with an extra format specifier to force the PEM RSA format.
Source https://serverfault.com/a/941893

Fix ssh-keygen command for newer Mac OS versions

---

assets/scss/main.scss

currently only links in content are cyan, other links are blue on hover

use blue color for all links instead of cyan

---

content/releases-and-versions/versions2.md

- Renamed the existing versions page to 'MacOS build machine specification (Xcode 11)'
- Added a new page for the base image with Xcode 12 called 'MacOS build machine specification (Xcode 12)'

Add base image details for Xcode 12

---

content/publishing-yaml/distribution.md

This pull request adds basic information on how to use Codemagic to publish web applications to Firebase Hosting. While trivial, there seem to be users who need confirmation that it works and help setting it up.

Add info about publishing to Firebase Hosting

---

content/publishing-yaml/distribution.md
content/publishing-yaml/public-dashboards.md
content/teams/teams.md

- Added a new page about public dashboards to the Publishing category
- Mentioned the feature in the documentation for teams

Document public dashboards

---

content/getting-started/yaml.md

The `branch_patterns` was defined at the same level as the `triggering`. It should be under the `triggering` as a **sub-property**. 
Removed the `branch_patterns` property as here only a brief of the properties at the same level (under `my-workflow`) are shown.

[Docs - Getting Started] Remove branch_patterns as it is in different level

---

content/getting-started/building-a-react-native-app.md

Building my android project locally caused a failure that the versionCode must be a positive integer greater than 0.

Change default build number to 1 instead of 0

---

content/publishing/email-and-slack-notifications.md

With new granular permissions Codemagic Slack app cannot see or publish to private slack channels, but it is possible once the app has been added to the private channel. This PR improves docs to cover how to publish to private Slack channels.

Update how to publish to private channels in Slack

---

content/publishing-yaml/distribution.md

This is the env var which we respect, but it's not reflected in docs. Probably may be useful to somebody. Please rephrase in any way needed.

add google play track env var

---

content/building/webhooks.md
content/flutter/automatic-build-triggering.md

- Updated the content type for GitHub webhooks
- Removed the note that PR triggers in UI settings are not supported for self-hosted repositories

Update webhook and triggers information

---

content/code-signing-yaml/signing-ios.md
content/code-signing/ios-code-signing.md

Hugo has a nice [youtube shortcut](https://gohugo.io/content-management/shortcodes/#youtube) for embedding videos.

Add automatic ios code signing youtube video

---

content/flutter/custom-scripts.md
content/getting-started/yaml.md
content/specs/versions-linux.md
content/specs/versions.md
content/specs/versions2.md
content/specs/versions3.md

I find it strange to have 12+ and 12.5+ names for machines since 12+ semantically includes 12.5+. Better to put the range there.
Also previous `See the default software versions on Codemagic build machines` pointed to macos with xcode 11, which could be a bin confusing since the default versions there are different, which includes such important soft as cocoapods, dart, docker etc. So better to list all the machines.
Added java and emulators info manually to not wait for base image updates, especially since we don't do base image update for older xcode machines.
Changed `#!/usr/bin/env python` to `#!/usr/bin/env python3` since on not xcode 12.5+ machines it resolves to python 2.7

update machine specifications with java and emulators, and allow to choose java

---

content/code-signing-yaml/signing-ios.md

This makes the code snippet slightly more flexible / ready to execute, such that people can have some certs with passphrases, and some without.

Tweak example for FCI_CERTIFICATE decoding

---

content/getting-started/building-a-react-native-app.md
layouts/shortcodes/github.html

Update to the React Native documentation so it links to the React Native demo project on GitHub.

React Native link to GitHub project

---

content/knowledge-base/validate-yaml.md

Removed configuration example for VS Code
Mentioned that schema are available by default in Android Studio and VS Code

remove example

---

content/getting-started/building-a-flutter-app.md
content/getting-started/building-a-native-android-app.md
content/getting-started/building-a-native-ios-app.md
content/getting-started/building-a-react-native-app.md
content/getting-started/building-an-ionic-app.md

As a V1 of linking docs and sample projects, I've added links to the github repositories from each codemagic.yaml starter file workflow example.

Add links to sample projects in codemagic.yaml getting started guides.

---

content/building/environment-variables.md
content/getting-started/building-a-native-android-app.md
content/getting-started/building-a-react-native-app.md
content/getting-started/building-an-ionic-app.md
content/getting-started/building_a_native_app_with_flutter_module.md
content/specs/machine-type.md

Xcode update from [12.4](https://docs.codemagic.io/specs/versions2/) to [12.5](https://docs.codemagic.io/specs/versions3/) broke builds based on the examples because of the change of the Android SDK path. This PR prevents misleading users in the future.
https://github.com/codemagic-ci-cd/codemagic-sample-projects/pull/2 to update sample projects

Android sdk path updates

---

content/code-signing-yaml/signing-macos.md

I cleared up encryption information and fixed a bug with app packaging.
Duplicates changes from https://github.com/codemagic-ci-cd/codemagic-docs/pull/339

Update macos signing docs

---

content/testing/running-automated-tests.md
content/testing/static-code-analysis.md

The previous description implies that a build will stop immediately if a test fails, but the checkbox is related to the whole test step, and all the enabled tests will run.
Inspired by https://codemagicio.slack.com/archives/CEKE2KZ37/p1621004312408700

rephrase "stop build if tests fail" description

---

assets/js/search.js
layouts/partials/search.html

I added [Algolia search](https://www.algolia.com/products/search/) using their [javascript client](https://github.com/algolia/algoliasearch-client-javascript).
TODO
Algolia "Flutter Android Signing" search
Existing "Flutter Android Signing" search

Add Algolia search

---

content/knowledge-base/add-a-git-tag-with-app-version.md
content/publishing/beta-deployment-with-fastlane.md

I was using code from https://docs.codemagic.io/knowledge-base/add-a-git-tag-with-app-version/. That started failing when I started using Linux VMs.
It appears that https://docs.codemagic.io/publishing/beta-deployment-with-fastlane/ would suffer from the same issue. There might be a way to support zsh instead or sh directly, but I wasn't sure what you would prefer so I defaulted to bash to just get it done.

Provide users with scripts that are compatible with both MacOS and current Linux VMs

---

content/building/encrypting.md

- The location for accessing the interface to encrypt environment variables has changed
- Also added a note about using encrypted environment variables across teams

Update due to UI changes

---

content/testing-yaml/testing.md

Tested the commands and updated the commands for `integration_test`.
Notes on some changes;
`-d <device_id>` is required since now all Flutter channels have web is enabled by default, without this, `integration_test` would target web unintentionally. 
`-d web-server` is required to target `non-web` platform for release mode, if you omit  it, release mode test will fail.

Update Flutter integration tests 

---

content/building/access-private-git-submodules.md

We actually show the message about adding the SSH keys to the agent during the "Fetching app sources" step, not during "Preparing build machine"

Minor correction in SSH keys docs

---

content/publishing-yaml/distribution.md
content/publishing/publishing-to-app-store.md

Update App Store Connect publisher documentation to reflect 
- the updated authentication method using App Store Connect API keys, and
- highlight the possibility to automatically submit the uploaded binary to TestFlight.

App store connect publisher documentation updates

---

config.yml
content/code-signing/android-code-signing.md
content/code-signing/ios-code-signing.md
content/code-signing/macos-code-signing.md
content/publishing/beta-deployment-with-fastlane.md
content/publishing/email-and-slack-notifications.md
content/publishing/publish-release-notes.md
content/publishing/publishing-to-app-store.md
content/publishing/publishing-to-codemagic-static-pages.md
content/publishing/snap-store.md

- Replace references to the Publish section with Distribution (for code signing and stores) or Notifications (email or Slack)
- Rename the Publishing category to Distribution and notifications

Reorganize publishing section

---

content/building/build-versioning.md

I think for most use cases where people copy and paste this script they will forget to `cd` into the ios directory.

CD into iOS folder before running agvtool

---

content/getting-started/building-a-flutter-app.md
content/getting-started/yaml.md

Flutter for some reason copies the identical apk to multiple folders - thus with the paths we recommend currently, we export three artefacts with the same name, which is confusing for the users (the md5 checksum is the same - meaning they literally are identical). The change to export more specific paths is already deployed live.

Specify android paths

---

content/getting-started/other.md

Update docs about the need to use a personal access token when a private GitHub repo is added over HTTPS.

Add note about personal access token

---

content/integrations/sonarcloud-integration.md

Added SonarCloud integration to the docs with links to an iOS and Android sample project which have readme files that explain how to configure the integration for each platform.

SonarCloud integration guide added

---

content/variables/environment-variable-groups.md

Replacing deprecated route 'building' from the section links to match the page's route.

Improvement: update section links to match route

---

content/variables/environment-variables.md

Minor update to clarify FCI_BUILD_DIR as being INSIDE the cloned repo.

Minor documentation update for FCI_BUILD_DIR

---

content/yaml-testing/firebase-test-lab.md

Env Variable groups and no base64 encoding required.

Fix: Firebase - Env Variable groups

---

config.yaml
layouts/shortcodes/include.html

If you need to have some content in multiple files without duplicating, you can create a file in `/content/partials/` and use the content of this file in other markdown files with `include` shortcode.
File: `/content/partials/a.md`
Include it as `{{< include "/partials/a.md" >}}`
If it's a markdown file, it should start with 
```
---
---
```
Don't put partial content files to other directories. Or if you do so, include them to `ignorefiles` in config.

add "include" shortcode

---

assets/js/article.js
config.yaml
content/custom-menu-position/ios-provisioning.md
content/yaml-testing/ios-provisioning.md
layouts/partials/breadcrumbs.html
layouts/partials/sidebar.html

- Added a new page: iOS device registration. It's currently available in the Testing category in Yaml view only.

Add docs about iOS device registration

---

content/yaml-testing/firebase-test-lab.md

Firebase project ID should be provided not the project name to `FIREBASE_PROJECT` environment variable
Otherwise, the following error will be thrown in Codemagic build
```console
+ gcloud --quiet config set project Triage-Companion
ERROR: (gcloud.config.set) The project property must be set to a valid project ID, not the project name [Triage-Companion]
To set your project, run:
$ gcloud config set project PROJECT_ID
or to unset it, run:
$ gcloud config unset project
```

fix firebase project instruction

---

content/billing/pricing.md

Added links to sign up & pay as you go for sign up and billing.
This is primarily to run an a/b test replacing the pricing section on site with docs

Changes to pricing page for the new a/b test

---

content/knowledge-base/firebase-crashlytics-dsym-uploading.md

The current path to dSYM archives, `~/build.xcarchive` doesn't usually exist. Instead, we should use the usual paths for different Xcode versions

Fix: path to dSYM archive

---

content/yaml-code-signing/signing-ios.md

I've added some more details about the CERTIFICATE_PRIVATE_KEY environment variable. This value is for providing the private key of the iOS Distribution certificate. You can use an existing iOS Distribution certificate private key, or create a new private key and let the Codemagic CLI tools create a new iOS Distribution certificate.

Add more details about CERTIFICATE_PRIVATE_KEY

---

content/yaml-quick-start/building-a-snap-package.md

The Snapcraft Build environment vars isn't properly defined:
```yaml
workflows:
snap-build:
name: Snapcraft Build
instance_type: linux
environment:
SNAPCRAFT_BUILD_ENVIRONMENT: host
scripts:
- name: Create a snap
script: snapcraft snap --output flutter-codemagic-example.snap
artifacts:
- '**/*.snap'
```
It is missing`vars`. Fixed to this:
```yaml
workflows:
snap-build:
name: Snapcraft Build
instance_type: linux
environment:
vars:
SNAPCRAFT_BUILD_ENVIRONMENT: host
scripts:
- name: Create a snap
script: snapcraft snap --output flutter-codemagic-example.snap
artifacts:
- '**/*.snap'
```

Fix snapcraft build yaml config

---

content/yaml-quick-start/building-a-unity-app.md

- Change from Bash script to Python to activate the license, export apps, and return license so it works on Windows VMs too. 
- Add workflow example of how to build Unity Windows app.

Update documentation for running Unity builds on Windows VMs

---

content/yaml/yaml-getting-started.md

Documentation for defining reusable sections under `definitions` and expanding them elsewhere using aliased mapping

Add aliased mapping under reuse sections

---

content/yaml-quick-start/building-a-unity-app.md

To simplify set up, the Unity activation, exporting of the iOS or Android project and license return is now done in the codemagic.yaml instead of an external Python script. 
Also, removed references to building for Windows desktop as these docs are currently for mobile platforms.

Remove Python script from Unity docs

---

assets/js/article.js
assets/scss/_article.scss
assets/scss/modules/_help-footer.scss
assets/scss/modules/_preference-switch.scss
assets/scss/modules/_sidebar.scss

- Prevent tables overflow (they had min-width set for cells).
- Reduce sidebar width to fit more content on 1001-1160px width.
- Make footer-support block layout adaptive.

improve tablet size view

---

content/yaml-code-signing/signing-ios.md

Update the text in bullet points for glancing over the text. 
For the manual signing, added detailed docs with the assumption that developers may directly land on this section.

Code Signing Docs

---

content/variables/using-environment-variables.md

This can be merged after changes regarding multiline par parsing have been deployed.

Add multiline example to env vars

---

content/yaml-publishing/app-store-connect.md

https://docs.codemagic.io/yaml-publishing/distribution/#app-store-connect was broken as the link wasn't aliased.

Add alias to keep old links working

---

content/billing/pricing.md

Unity is now available on build machines so it's not necessary to have a dedicated host to get started building Unity projects now.

Remove Unity section

---

content/yaml-quick-start/building-a-vr-oculus-app.md

Hello,
here is a PR to add a new doc page (in the YAML quick start section) on how to setup a Codemagic workflow to build and publish a Unity VR app for Oculus. It describes how to configure the Codemagic app environment variables, the Unity project settings and the codemagic.yaml file to distribute a VR app on an Oculus release channel using the Oculus CLI tools.
Some parts are copied from [the other Unity guide in the doc](docs.codemagic.io/yaml-quick-start/building-a-unity-app/), I hope it's fine.
(Based of my previous article on Codemagic's blog: https://blog.codemagic.io/building-and-publishing-a-vr-unity-game-for-oculus-with-codemagic/)
Cheers! :)

Add Unity Oculus VR + Codemagic build & publish guide

---

content/yaml-testing/emulator-wtf.md

[emulator.wtf](https://emulator.wtf) is a cloud Android emulator laser-focused on performance, delivering 2-5x gains over alternatives like Firebase Test Lab.
Add documentation on how to run instrumentation tests with [emulator.wtf](https://emulator.wtf).
NOTE: do not merge until `ew-cli` is available on the build machines.

Add emulator.wtf integration docs

---

content/configuration/build-versioning.md
content/yaml-quick-start/building-a-flutter-app.md
content/yaml-quick-start/building-a-react-native-app.md
content/yaml-quick-start/building-a-unity-app.md

Since [`google-play get-latest-build-version`](https://github.com/codemagic-ci-cd/cli-tools/pull/215) will allow using custom release tracks it would be nice if CM docs reflected that possibility too.
Other changes:
- remove obsolete references environment variables with base64 encoded file values,
- unify CLI args usage formatting,
- remove Google reference from example package name.

Android app build versioning

---

content/yaml-quick-start/building-a-unity-app.md

When using addressables in Unity you should use the -buildTarget flag.

Add correct build targets for Unity builds

---

content/yaml-quick-start/building-a-native-ios-app.md

Small developer experience improvement while copying the command from the docs so that developers do not have to update 14.5 to 15.4 as `latest`, `edge` has iOS 15.4 simulators.

Update iOS Simulator to 15.4

---

content/flutter-testing/testing-widgets.md

We introduce a default Flutter version for our build machines. Currently default will be resolved to
* 3.0.0 for all Xcode 13+ machines, Linux, and Windows
* 2.10.5 for Xcode 11 and Xcode 12 machines
The default version will be used if Flutter version is not specified (before it was stable) and should be recommended for all non-Flutter projects.
Also we changed the logic behind stable version. Now, it always matches the official Flutter stable channel. If the version is not pre-installed on a builder machine, it will be downloaded automatically.

Feature: default Flutter version

---

layouts/shortcodes/markdown.html

Enables using markdown within nested dynamic tabs. A simple copy of the "notebox" shortcode but without setting class.

Add "markdown" shortcode

---

content/partials/build-versioning-android.md
content/partials/code-signing-android.md
content/partials/code-signing-ios.md
content/partials/create-yaml-intro.md
content/partials/publishing-android-ios.md
content/yaml-quick-start/building-a-react-native-app.md

API connect key does not need base64 encoding

fix a typo

---

content/getting-started/monorepo-apps.md

A proposal to add the blog [How to manage your Flutter monorepo](https://blog.codemagic.io/flutter-monorepos/) to the docs. Suggestions are welcome :)

Mention blog article "How to manage your Flutter monorepo" in `monorepo-apps.md`

---

content/yaml-quick-start/building-a-react-native-app.md

The `androd` folder caused a build error when I followed the guide
```
Set Android SDK location
/var/folders/m7/h1mg7c7x40ddjz6mxjxm3htr0000gn/T/build_script_6_1_q6yej6s1: line 3:  /Users/builder/clone/android/local.properties: No such file or directory  
```

Correct path to local.properties

---

content/yaml-quick-start/building-a-unity-app.md

Previously the build script only had items for Android and iOS. I think it's worth adding workflows for Windows there as well. Maybe there are other parts of the Codemagic Unity docs that we need to pay attention to, but the build script is obviously missing. Borrowed one from an upcoming article by Mina.

Added build script for Windows to Unity docs

---

content/integrations/emerge-integration.md

**Emerge Tools** helps to monitor and reduce app size with insights for instant savings. It provides continuous monitoring to write smaller, better code by profiling binary size on every pull request. 
This integration shows how you can automatically leverage their Fastlane plugin to upload the archives to Emerge using the Codemagic workflow configuration file when a PR is created.

Add Emerge integration

---

content/knowledge-codemagic/build-versioning.md
content/partials/quickstart/build-versioning-android.md
content/yaml-quick-start/building-a-kmm-app.md
content/yaml-quick-start/building-a-native-android-app.md
content/yaml-quick-start/building-a-react-native-app.md
content/yaml-quick-start/building-an-ionic-app.md

Documentation https://docs.codemagic.io/yaml-quick-start/building-a-native-android-app/ Build versioning step 7 example has mistake where variable LATEST_BUILD_NUMBER is used instead of LATEST_GOOGLE_PLAY_BUILD_NUMBER.

Fix instructions step for android build versioning

---

content/yaml-quick-start/building-a-native-android-app.md

Problem: No artifact is generated and is therefore not available for download after the build.
Solution: Change the path
From: - android/app/build/outputs/**/*.aab
to: - app/build/outputs/**/*.aab 
More details:
If you follow the steps in the documentation, no artifact will be created as mentioned above. The following message appears:
"
== Gathering artifacts ==
No artifacts were found
"
If you make the changes I suggested and follow the documentation otherwise, the .aab artifact is created successfully and is then also available for download.
Furthermore, if you look at the sample project from codemagic, the path is also given as I suggested: https://github.com/codemagic-ci-cd/codemagic-sample-projects/blob/main/android/android-espresso-demo-project/codemagic.yaml
Therefore I would …

Updating building-a-native-android-app.md, changing artifact path

---

content/yaml-quick-start/building-a-native-android-app.md
content/yaml-testing/testing.md

**Problem:** Indentation of the "test_report" is not correct and leads to a "Configuration file error".
**Solution:** Correct the indentation of the test_report:
From:
- name: test
script: ./gradlew test
test_report: app/build/test-results/**/*.xml
to: 
- name: test
script: ./gradlew test
test_report: app/build/test-results/**/*.xml
**More details:**
The indentation in the yaml file of the "_test_report_" is not correct and therefore leads to a visible "_Configuration file error_" in the yaml overview on the codemagic page itself.
I could only test this with a native Android app, but it's possible that the indentation is also wrong for the other test cases in the documentation (flutter, ..). For "Native macOS" the indentation in the documentation should be correct and is as I suggested. …

Updating testing.md fixing wrong indentation for "test_report"

---

.github/workflows/deploy.yml

Currently deployment builds have the warning:
```
Node.js 12 actions are deprecated. For more information see: [GitHub Actions: All Actions will begin running on Node16 instead of Node12 | GitHub Changelog](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/). Please update the following actions to use Node.js 16: actions/checkout, actions/checkout
```
Updating checkout from v2 to v3 solves the issue, using node 16 by default. 
https://github.com/actions/checkout#whats-new

Use checkout@v3

---

content/flutter-testing/static-code-analysis.md
content/yaml-testing/dart-code-metrics.md

The actual behaviour differs from what is described in the documentation, as the global package is always ran when dart code metrics is enabled.

Sync docs with behaviour

---

content/specs/versions-macos.md

trello [task](https://trello.com/c/3jMM2rav/1892-confirm-versions-on-xcode-12-images)

fix macos tab labels for 12.0+ and 12.5

---

content/flutter-notification/email-and-slack-notifications.md
content/yaml-notification/email.md
content/yaml-notification/slack.md
content/yaml-publishing/build-dashboards.md

As per the soon-to-be update to the Codemagic product, artifact links published via e-mail or slack will have configurable expiration dates.
This can be merged after the features have been deployed to the product.

Update artefact link expiry information

---

content/knowledge-codemagic/machine-type.md

As the Intel Mac mini is now deprecated, update the machine type to consist only of Mac Pro and M1 Mac mini

Update Machine Type

---

content/billing/pricing.md
content/knowledge-codemagic/machine-type.md
content/yaml-basic-configuration/yaml-getting-started.md

Reflect the change in the UI whereby macOS Premium VM was renamed to macOS Intel VM.

Machine type changes

---

content/partials/quickstart/code-signing-ios-add-provisioning-profile.md

While it is mentioned for the workflow editor that you are required to upload provisioning profiles for each app extension, it is helpful to mention it for yaml too.

Update iOS Code Signing to mention App Extensions for Profiles

---

content/yaml-basic-configuration/environment-variables.md

Clone depth defaults:
* Tags - 1
* PR destination - 1
* Branch - 50
The defaults can be overwritten by setting the preferred depth in `CM_CLONE_DEPTH` env var.
Additionally, we have `CM_CLONE_UNSHALLOW` env var. If it’s set to true, clone depth would be set to maximum for all cases
For PR source, the depth is infinity and can't be overwritten with environment variables. It is to ensure that we could always merge source branch into destination during a build

Improvement: repository cloning depth

---

content/yaml-basic-configuration/environment-variables.md

GitHub PR webhook payload specifies latest destination commit, instead of the latest commit that is also available in source branch
This caused a few SWWs since the deployment of clone depth PRs
This seem to happen when PR destination branch had new pushes that are not yet merged in the source branch

Fix: increase default clone depth for destination

---

content/rest-api/teams.md

Task: https://trello.com/c/Q9FqpxCy/2037-documentation-for-user-management
New page for teams API added to documentation with the endpoints suggested.
Probably for our users it is also necessary to document `GET /:team_id` , to have direct access to "invitation status" and "user_ids" of the team.

add new page for teams API

---

content/knowledge-others/install-unity-version.md

we now have 2021.3.23f1 and 2022.2.16f1 archives available for x86_64
✅ tested both versions on mac Pro

add 2021.3.23f1 and 2022.2.16f1 to unity versions

---

content/partials/specs/versions-macos-m1-xcode-14-2.md

Since April 19, XCode 14.3 is the default option for Mac M1. This PR updates this information in the docs because it still said that XCode 14.2 is the default option.
From the [GitHub discussion](https://github.com/orgs/codemagic-ci-cd/discussions/1545):
> As you may already know, Apple released Xcode 14.3 on March 31. This version requires a Mac running macOS Ventura 13.0 or later, which may cause breaking changes when switching from a macOS Monterey 12.x build machine. Please ensure your Xcode projects are updated locally before updating CI/CD configuration on Codemagic.
> 
> Additionally, Xcode 14.3 is only available on Mac mini M1 machines and is not available on Intel-based Mac Pro or older machines. The highest available Xcode version on Intel-based machines is Xcode 14.2. Please …

Update that XCode 14.3 is the default option for Mac M1

---

content/flutter-testing/static-code-analysis.md
content/yaml-testing/dart-code-metrics.md

Update workflow editor and yaml docs with the note about the upcoming deprecation of the dart_code_metrics plugin.

Dart Code Metrics deprecation note

---

content/troubleshooting/common-ios-issues.md

Updated common iOS issue page about the "A required agreement is missing or has expired" error

A required agreement is missing or has expired

---

content/yaml-basic-configuration/environment-variables.md

With this [PR](https://github.com/codemagic-dev/builder_worker/pull/103), we add a new environment variable available for all builds, so we should add it to our docs.

add env var CM_WORKFLOW_NAME

---

content/_index.md
content/flutter-configuration/flutter-projects.md

This adds utm tags that were missed out in previous addition of the links to the codelab.

add utm tags to codelab links

---

content/flutter-code-signing/ios-code-signing.md

For some reason this video embed was lost at some point, so re-instating it, as its still relevant to the topic.

reinstate Flutter iOS auto codesigning video embed

---

content/yaml-basic-configuration/yaml-getting-started.md
static/codemagic-yaml-cheatsheet.html

This adds the prerendered html for a Codemagic YAML cheatsheet created using the tooling from https://github.com/codemagic-ci-cd/codemagic-yaml-cheatsheet with extraneous html removed and links to it from the existing docs YAML getting started page.

add pre-rendered yaml cheatsheet html page

---

content/knowledge-firebase/firebase-crashlytics-dsym-uploading.md

added a separate, much more visible step for uploading dSYM file to Firebase, since we have a lot of queries on how to do it with wfe

separated instructions for wfe and yaml for uploading dSYM file to Firebase

---

content/flutter-testing/static-code-analysis.md

Changed the order and wording of the docs to be a bit clearer. Added a script to retrieve an optional test result text file.

Update static-code-analysis.md for WFE on how to retrieve test results as a text file

---

content/rest-api/builds.md

I wondered how to change the `instance_type` via the API. Unfortunately, I couldn't find any information about this in the documentation. Therefore, I tried `instance_type` first. This hasn't worked. Then I tried `instanceType`. This worked :)
Therefore, I thought, it would be maybe helpful to mention this in the documentation ["Pass custom build parameters" section](https://docs.codemagic.io/rest-api/builds/#pass-custom-build-parameters).

Add example on how to set the `instance_type` via the API

---

content/partials/specs/versions-macos-intel-xcode-12-5.md
content/partials/specs/versions-macos-intel-xcode-13-0.md
content/partials/specs/versions-macos-intel-xcode-13-3.md
content/partials/specs/versions-macos-intel-xcode-14-2.md

these were accidentally added back to the specs due to automation scripts

remove reappeared mac minis

---

content/knowledge-others/install-unity-version.md

It's now possible to install and run Unity on Apple Silicon Macs

Improvement: use x86_64 Unity for both Apple Silicon and Intel processors

---

content/knowledge-codemagic/machine-type.md

Documentation changes to reflect build machine naming changes and the deprecation of Standard Linux instance type: https://github.com/orgs/codemagic-ci-cd/discussions/2063

Deprecation: Standard Linux instance type

---

content/yaml-basic-configuration/yaml-getting-started.md
content/yaml-running-builds/starting-builds-automatically.md

We now have a new triggering event called `pull_request_labeled` which triggers builds when a new label is added to a PR.

Add new `pull_request_labeled` triggering event

---

content/partials/code-signing-macos.md
content/partials/quickstart/code-signing-macos.md
content/yaml-quick-start/building-a-flutter-app.md
content/yaml-quick-start/building-a-unity-app.md

Some Codemagic CLI tools were renamed in https://github.com/codemagic-ci-cd/cli-tools/pull/386. This PR ensures that deprecated names are not referenced in current docs.

Update commands to list and create certificates

---

content/yaml-testing/emulator-wtf.md

This can be needed for certain testing frameworks.
E.g. here: https://github.com/leancodepl/patrol/issues/2005

Update emulator-wtf.md with Android Test Orchestrator example

---

content/notes/release-notes.md

We've had Xcode 15.3 available for a while but it was not mentioned in the release log.

Add 15.3 Beta to release log

---

content/flutter-code-signing/ios-code-signing.md
content/flutter-code-signing/macos-code-signing.md
content/flutter-publishing/publishing-to-app-store.md

This PR updates outdated "Creating an App Store API key for Codemagic" sections to use `partials/app-store-connect-api-key.md`. This was updated in https://github.com/codemagic-ci-cd/codemagic-docs/pull/2373

Update "Creating an App Store API key for Codemagic" sections

---

content/yaml-running-builds/starting-builds-automatically.md

There is an example [in the docs](https://docs.codemagic.io/yaml-running-builds/starting-builds-automatically/#:~:text=Example%202.%20Setting%20source%3Atrue%20and%20branch%3Amain%2C%20will%20trigger%20the%20build%20on%20the%20main%20branch%20once%20the%20pull%20request%20has%20been%20merged%20from%20the%20feature%20branch%20into%20the%20main%20branch.) that is showing how to trigger a build on the main branch when a feature branch is merged into it, but in order to this be valid, it needs to have the push event as well

Triggering build on pull_request update

---

content/knowledge-others/build-dashboards.md
content/knowledge-others/github-checks.md

Some generic docs are available in the left menu only for yaml but not for Flutter Workflow Editor. For example, Build dashboards and GitHub checks.
Added this info on the Various section in WFE

added github checks and build dashboards page to WFE Various section

---

content/yaml-basic-configuration/yaml-getting-started.md

We only support installing another version of Ruby on macOS at the moment.

using non-default ruby only for macOS

---

content/rest-api/applications.md

A separate section about getting the variable ID in Applications API is unnecessary as it duplicates the "Fetch variables" section. 
Fixed the formatting and rephrased the note about workflow information for codemagic.yaml workflows.

Remove section about getting variable ID

---

content/partials/firewall.md

`66.185.17.82/32` is correct address, but we should use subnet address. 
So users no need to update firewall rules every time we add more hosts.

fix Milwaukee IP address

---

content/partials/quickstart/publishing-app-store.md
content/partials/yaml-publishing-app-store-connect-environment-variables.md
content/partials/yaml-publishing-app-store-connect-team-integration.md

**Background**
Version [0.51.0](https://github.com/codemagic-ci-cd/cli-tools/releases/tag/v0.51.0) of Codemagic CLI tools added support for [releasing App Store versions in phases](https://developer.apple.com/help/app-store-connect/update-your-app/release-a-version-update-in-phases) and this feature is also supported by Codemagic YAML workflows.
**What was done**
Update YAML App Store publishing docs with information about releasing App Store version in phases: include `publishing -> app_store_connect -> phased_release` key with description in YAML workflow snippets where App Store Connect publishing with App Store submission is enabled.

Document releasing App Store version in phases

---

content/partials/yaml-validate.md

The link for the schema in the documentation is wrong and points to an old schema. Updated the schema link to the latest one.

Update yaml-validate.md to point correct link to the schema

---

content/knowledge-codemagic/build-inputs.md
content/knowledge-codemagic/caching.md
content/knowledge-codemagic/codemagic-cli-tools.md
content/knowledge-codemagic/flutter-screenshots-stores.md
content/rest-api/builds.md

Add new documentation entry to YAML -> Advanced configuration -> Build inputs.
Added article contains the following information:
- describes what "start build inputs" are,
- how to set up build inputs in YAML workflows,
- how to use build inputs when starting builds manually and via API.
**TODOs**

Add documentation entry for start build inputs

---

content/yaml-publishing/app-store-connect.md

Fix Typo in app-store-connect.md

---

content/yaml-quick-start/migrating-from-app-center.md

h4 headings are not linkable. I'm bumping heading sizes to h3 to be able to link to the subsections from other pages.

Update heading sizes in App Center migration guide

---

content/yaml-quick-start/migrating-from-app-center.md

Promote the Discord link to allow users to connect and share experiences with other users. 
The invite link should take users to the dedicated App Center support channel in the desktop app.

Add a note with Discord invite

---

content/yaml-notification/status-badges.md

Fix the latest build url in the badge markdown.

Fix latest build url in badge markdown

---

content/partials/yaml-publishing-app-store-connect-environment-variables.md
content/partials/yaml-publishing-app-store-connect-team-integration.md

We no longer require submitting builds to TestFlight beta review as a prerequisite to distributing to beta groups.

Remove TestFlight submission requirement for beta groups

---

content/partials/firewall.md

Load IP addresses dynamically from API

Feature: dynamically load IP addresses

---

content/getting-started/teams.md

There have been changes to how apps are managed in teams. This PR updates how new apps can be added to teams and adds a few notes about transferring apps.

Update managing team apps

---

content/partials/app-store-connect-api-key.md
content/partials/integrations-setup-app-store-connect.md

iOS code signing sections that describe App Store Connect API key generation process reference outdated App Store Connect links.

Update App Store Connect API URLs

---

content/billing/pricing.md
content/knowledge-others/install-unity-version.md
content/specs/versions-macos.md
content/troubleshooting/common-android-issues.md
content/yaml-basic-configuration/yaml-getting-started.md
content/yaml-quick-start/building-a-unity-app.md
content/yaml-quick-start/building-a-vr-oculus-app.md
static/codemagic-yaml-cheatsheet.html

Remove Intel machines specs from docs as well as references to `mac_pro`. 
Further cleanup will follow in https://github.com/codemagic-ci-cd/codemagic-docs/pull/2698

Cleanup after Intel deprecation

---

content/billing/pricing.md
content/getting-started/about-codemagic.md
content/knowledge-codemagic/machine-type.md
content/knowledge-others/import-variables-from-env-file.md
content/knowledge-white-label/white-label-apps-overview.md
content/partials/monorepo-apps.md
content/partials/quickstart/create-yaml-intro.md
content/partials/white-label-apps.md
content/rest-api/builds.md
content/troubleshooting/common-ios-issues.md
content/yaml-basic-configuration/yaml-getting-started.md
content/yaml-code-signing/ios-simulator-builds.md
content/yaml-quick-start/building-a-dotnet-maui-app.md
content/yaml-quick-start/building-a-native-android-app.md
content/yaml-quick-start/building-a-native-ios-app.md
content/yaml-quick-start/building-a-react-native-app.md
content/yaml-quick-start/building-a-unity-app.md
content/yaml-quick-start/building-a-vr-oculus-app.md
content/yaml-quick-start/migrating-from-app-center.md
content/yaml-quick-start/white-label-getting-started.md
content/yaml-testing/testing.md

Now that we have removed M1 machines, we can remove outdated references to M1 instances.

Remove references to M1

---

content/yaml-quick-start/building-a-unity-app.md

Fix for https://github.com/codemagic-ci-cd/codemagic-docs/issues/2824

Add link for installing different Unity versions page to the Unity docs page

---

assets/js/article.js
assets/scss/main.scss

In order to fix https://github.com/codemagic-dev/codemagic/issues/653, I had to adjust order of **on ready** calls:
1. `setInitialPreference` to set relevant items be displayed in the menu
2. `openActiveCategory` to open active category
3. Finally, after relevant items are displayed and positioned, `scrollMenuToActive` to scroll to active menu item
Adjusting the order allowed to remove duplicate `openActiveCategory` call.
Scroll to active menu item works for:
✅ YAML menu
✅ Workflow editor menu

Fix: scroll menu to active item

---

.github/workflows/deploy.yml

the `hugo deploy` command was removed from the standard package, more information here https://github.com/gohugoio/hugo/issues/12994

fix hugo deploy

---

content/billing/pricing.md

* Change wording from certified to SOC2 assessment
* Adding GCP Marketplace beside AWS

SOC 2 and GCP Marketplace availability

---

content/integrations/codepush-integration.md

After testing an update against a deployment channel, it is possible to promote it to destination channels

CodePush updates promoting downstream

---

content/yaml-basic-configuration/yaml-getting-started.md

Add link to page on configuring configuring caching for builds and removed `mac_mini_m2` from `instance_type` only available for teams and users with billing enabled.

Yaml Getting Started Documentation Review

---

content/specs-macos/xcode-16-0.md
content/specs-macos/xcode-16-2.md

page titles did not get updated automatically after Xcode 16.2 became default, here is a fix

minor bugfix/update page titles

---

content/partials/app-preview-builds.md

First codemagic.yaml examples of how to build `.app` for Flutter projects.
Additional Framework samples to be added later.

How to build iOS .app binaries for Flutter apps

---

content/flutter-publishing/shorebird.md

Instead of linking to the Shorebird codemagic.yaml guide, provide instructions for creating the token in documentation.

Add section about token generation

---

content/partials/app-preview-builds.md

FLUTTER_BUILD_MODE=debug is required for building the simulator version

Add Flutter build mode

---

content/billing/pricing.md

Removing $99/month pricing option

Monthly CodePush pricing

---

content/flutter-publishing/shorebird.md

When building a patch with Shorebird, Android and/or iOS release version cannot be empty.

Update instructions for setting the Android and iOS release version

---

config.yaml
content/specs-linux/ubuntu-20.04.md
content/specs-linux/ubuntu-24.04.md
content/yaml-basic-configuration/yaml-getting-started.md

- Replaced  `Linux machines` page with a section that holds all available images 
- Mark current linux image as default
- Added "ubuntu" to software versions inside Environment options

Add ubuntu image types docs

---

content/troubleshooting/common-issues.md

This pull request adds a new entry to the Common Issues section under Troubleshooting to help users resolve a frequent build error encountered when using localizations in Flutter. The error typically occurs when the necessary localization files are not generated during the build process, resulting in a ` Try correcting the name to the name of an existing getter, or defining a getter or field named  'AppLocalizations'.` error.
- Added a new entry to the Common Issues section under Troubleshooting.
- Added the solution to run the `flutter gen-l10n` command in the pre-build script.
-  The description is concise and follows the format of existing entries.
-  Log output and example scripts are included.
-  Links to official Flutter documentation are provided.
-  Reviewed and tested for …

Add troubleshooting section for Flutter build error with localizations

---

content/getting-started/teams.md

Highlighting that iOS and Android code signing configurations are not carried over when applications are moved from personal accounts to teams

App migration from Personal accounts to Teams
